const express = require('express')
const app = express()
const cors = require('cors')
const helmet  = require('helmet')
const compression = require('compression')
const morgan = require('morgan')
const path = require('path')
const fs = require('fs')
require('dotenv').config()
const bodyParser = require('body-parser')
const sequelize = require('./utils/db')
const expenseRoutes = require('./routes/routes')
const signupRoutes = require('./routes/signup')
const purchaseRoutes = require('./routes/purchase')
const premiumRoutes = require('./routes/premium')
const forgotPassRoutes = require('./routes/forgotPass')
const reportRoutes = require('./routes/report')
const User = require('./models/signup')
const Expense = require('./models/expenses')
const Order = require('./models/orders')
const ForgotPasswordRequests = require('./models/forgotPass')
const Downloadedfiles = require('./models/filesDownloaded')
const accessLogStream = fs.createWriteStream(path.join(__dirname, 'aceess.log'),
 {flag: 'a'});
app.use(cors())
app.use(helmet())
app.use(compression())
app.use(morgan('combined', {stream: accessLogStream}))
app.use(express.json())
app.use('/expense', expenseRoutes)
app.use('/signup', signupRoutes)
app.use('/expense/purchase', purchaseRoutes)
app.use('/premium', premiumRoutes)
app.use('/', forgotPassRoutes)
app.use('/report', reportRoutes)
User.hasMany(Expense);
Expense.belongsTo(User)
User.hasMany(Order)
Order.belongsTo(User)
User.hasMany(ForgotPasswordRequests)
ForgotPasswordRequests.belongsTo(User)
User.hasMany(Downloadedfiles);
Downloadedfiles.belongsTo(User)

sequelize
.sync()
// .sync({force: true})
.then(result => {
    app.listen(process.env.PORT || 3000); 
    console.log('app is running')
})
.catch(err => console.log(err))